### ISSUE TITLE
Bug with follow-around camera

### ISSUE THREAD

**Issue by joshuakatt** [joshuakatt/PixScout-A-2D-Odyssey#1]
There seems to be a small bug with the follow around camera. It only seems to be able to stop going out of the map edge when on the top left and right corners. But there's a glitch when I head over the two bottom corners of the map. The camera seems to have an issue.

**Comment by jess0605** [comment]
Hi! I'm interested. Can I solve this task?

**Comment by joshuakatt** [comment]
Sure, I'll assign it to you right away!

**Comment by joshuakatt** [comment]
Thanks for your contribution, Issue solved.
